packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  esbuild: false
  msw: false
  prisma: false
  sharp: false
  unrs-resolver: false
